name: Deploy from GHCR

on:
  workflow_run:
    workflows: ["Build and Push Container"]
    types: [completed]
    branches: [prod]
    #hellooo

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://${{ secrets.AZURE_WEBAPP_NAME }}.azurewebsites.net

    steps:
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ghcr.io/amri0faz31/petcareplus3/app:latest
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}

