name: Feature Branch Validation (.NET Only)

on:
  push:
    branches: 
      - 'feat/*'
      - 'fix/*'
      - 'hotfix/*'
    paths:
      - '**'

jobs:
  validate-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run Tests
      env: 
        ASPNETCORE_ENVIRONMENT: Testing
      run: dotnet test --no-build --configuration Release --verbosity normal
