name: PR to Production Validation

on:
  pull_request:
    branches: [prod, main]
    paths:
      - '**'

permissions:
  contents: read
  pull-requests: write

jobs:
  backend-comprehensive-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Release
      run: dotnet build --no-restore --configuration Release

    - name: Run API Unit Tests
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        ASPNETCORE_ENVIRONMENT: Testing
      run: dotnet test ./tests/PetCare.Api.Tests/PetCare.Api.Tests.csproj --no-build --configuration Release --verbosity normal

    - name: Run Integration Tests
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        ASPNETCORE_ENVIRONMENT: Testing
      run: dotnet test ./tests/PetCare.Integration.Tests/PetCare.Integration.Tests.csproj --no-build --configuration Release --verbosity normal
